# Copyright 2019, Oath Inc.
# Licensed under the terms of the Apache 2.0 license.  See the LICENSE file in the project root for terms

version: 4
shared:
    environment:
        CHANGELOG_FILENAME: docs/changelog.md

jobs:
    validate_codestyle:
        template: python/validate_codestyle
        requires: [~commit, ~pr]

    validate_dependencies:
        template: python/validate_dependencies
        requires: [~commit, ~pr]

    validate_lint:
        template: python/validate_lint
        requires: [~commit, ~pr]

    validate_security:
        template: python/validate_security
        requires: [~commit, ~pr]

    validate_test:
        template: python/validate_unittest
        requires: [~commit, ~pr]

    validate_documentation:
        template: python/documentation
        environment:
            DOCUMENTATION_PUBLISH: False
        requires: [~pr]

    generate_version:
        template: python/generate_version
        requires: [~commit, ~pr]

    publish_test_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
            TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        requires: [validate_test, validate_lint, validate_codestyle, validate_dependencies, validate_security, generate_version]

    verify_test_package:
        template: python/validate_pypi_package
        environment:
            PYPI_INDEX_URL: https://test.pypi.org/simple
        requires: [publish_test_pypi]

    publish_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
        requires: [verify_test_package]

    publish_documentation:
        template: python/documentation
        requires: [publish_pypi]
